### ISSUE TITLE
Weird looks on firefox

### ISSUE THREAD

**Issue by FMorschel** [Rexios80/flutter_autofill_test#1]
Hey! I say your sample on [the issue about autofill](https://github.com/flutter/flutter/issues/127694) and opened it on Firefox. When I have the time I can take a look at Flutter's issues and your code, to see whats going on here. But I just wanted to let you know this.

<details> 

<summary> Stable </summary>

![image](https://github.com/user-attachments/assets/2153950b-34b0-4f52-83d6-9b8f8b92d312)

</details>

<details> 

<summary> Beta </summary>

![image](https://github.com/user-attachments/assets/b896692f-f181-4d22-a797-854d47e4c31d)

</details>

<details> 

<summary> Master </summary>

![image](https://github.com/user-attachments/assets/e4ec0a20-2e46-446d-a490-87f90cf55085)

</details>

In any branch you open it, it goes up half of the screen. But the buttons' hitboxes stay in the same place they were meant to be.

**Comment by Rexios80** [comment]
Is this a Firefox specific issue?

**Comment by FMorschel** [comment]
When opening on Chrome it did open as it should, but I've not yet tested on other browsers. 

When I get home I can help you look for the problem. And test on other browsers. 

P.S.: I also saw that the latest stable (CP fixes) was released yesterday and the stable website was built 6 days ago.

**Comment by Rexios80** [comment]
I forced a build, but if you were having the issue on all channels before it probably didn't fix anything

**Comment by Rexios80** [comment]
Renders fine for me on latest Firefox

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/28979e0b-51b1-44ac-af2f-0fb4f884183b">

**Comment by FMorschel** [comment]
I've done some more testing. Disabling all my extensions made no difference, but opening it on a clean profile worked as intended. It must be some config I'm setting that for some weird reason is messing with it. No idea what it could be. I guess this could be closed then. If I ever find the culprit I can update this thread.
